FROM ritaakichik/jetson-ros2-ultralytics:latest-humble

# add user and his password
ARG USER=docker_yolov8_seg
ARG UID=1000
ARG GID=1000
# default password
ARG PW=user

ENV PYTHONPATH=/home/${USER}/colcon_ws/src/yolov8_seg:${PYTHONPATH}

RUN useradd -m -o ${USER} --uid=${UID} && echo "${USER}:${PW}" | chpasswd && adduser ${USER} sudo
WORKDIR /home/${USER}
RUN mkdir -p colcon_ws/src && chown -R ${UID}:${GID} /home/${USER}
USER ${UID}:${GID}